[project]
name = "judge-client"
version = "2.0.0"
description = "Client for Trojsten Judge API"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "pydantic>=2.11.4,<3",
    "requests (>=2.32.3,<3.0.0)",
]
